version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: techstore-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: TechStoreManager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    image: vanthanh180924/backend_techstore-api:latest
    container_name: techstore-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: