BEGIN;

-- ==========================================
-- 1. TẠO CÁC BẢNG (CREATE TABLES)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.addresses
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    address_detail character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_code character varying(20) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    district character varying(100) COLLATE pg_catalog."default" NOT NULL,
    district_code character varying(20) COLLATE pg_catalog."default",
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_default boolean,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ward character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ward_code character varying(20) COLLATE pg_catalog."default",
    user_id integer NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_knowledge_logs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    message_id bigint,
    query_timestamp timestamp(6) without time zone,
    source_data jsonb,
    CONSTRAINT ai_knowledge_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attributes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(50) COLLATE pg_catalog."default",
    filter_group character varying(50) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT attributes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.brands
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    logo_url character varying(255) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT ukpnhnc9urm6fro7oseu9vka70q UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    cart_id integer NOT NULL,
    product_variant_id integer NOT NULL,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.carts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    session_id character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    user_id integer,
    CONSTRAINT carts_pkey PRIMARY KEY (id),
    CONSTRAINT uk1ihnigm9j28oe6n2qkws6q13q UNIQUE (session_id),
    CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    image_url character varying(255) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    parent_id integer,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.chat_messages_ai
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    metadata jsonb,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tokens_used integer,
    session_id uuid,
    CONSTRAINT chat_messages_ai_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_session_ai
(
    id uuid NOT NULL,
    context_id integer,
    context_type character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    session_key character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    user_id integer,
    CONSTRAINT chat_session_ai_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.flash_sales
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    end_time timestamp(6) without time zone NOT NULL,
    flash_sale_price numeric(15, 2) NOT NULL,
    max_quantity_per_user integer,
    sale_stock_quantity integer NOT NULL,
    sold_quantity integer,
    start_time timestamp(6) without time zone NOT NULL,
    status integer,
    product_variant_id integer NOT NULL,
    CONSTRAINT flash_sales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_history
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    change_amount integer NOT NULL,
    created_at timestamp(6) without time zone,
    new_quantity integer NOT NULL,
    note character varying(255) COLLATE pg_catalog."default",
    previous_quantity integer NOT NULL,
    product_variant_id integer NOT NULL,
    reference_id integer NOT NULL,
    reference_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inventory_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_note_details
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    price numeric(15, 2),
    product_variant_id integer NOT NULL,
    quantity integer NOT NULL,
    inventory_note_id integer NOT NULL,
    CONSTRAINT inventory_note_details_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory_notes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    note text COLLATE pg_catalog."default",
    reason character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    supplier_name character varying(255) COLLATE pg_catalog."default",
    total_amount numeric(15, 2),
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    CONSTRAINT inventory_notes_pkey PRIMARY KEY (id),
    CONSTRAINT ukaxdxa94op9vrto30otc0ksr4d UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_serial_required boolean,
    option1_name character varying(50) COLLATE pg_catalog."default",
    option1_value character varying(50) COLLATE pg_catalog."default",
    option2_name character varying(50) COLLATE pg_catalog."default",
    option2_value character varying(50) COLLATE pg_catalog."default",
    option3_name character varying(50) COLLATE pg_catalog."default",
    option3_value character varying(50) COLLATE pg_catalog."default",
    price numeric(15, 2) NOT NULL,
    product_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    sku character varying(100) COLLATE pg_catalog."default",
    thumbnail character varying(255) COLLATE pg_catalog."default",
    total_price numeric(15, 2) NOT NULL,
    order_id integer NOT NULL,
    product_variant_id integer,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cancel_reason character varying(255) COLLATE pg_catalog."default",
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    company_address character varying(255) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    customer_email character varying(150) COLLATE pg_catalog."default",
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discount_amount numeric(15, 2),
    final_amount numeric(15, 2) NOT NULL,
    goship_shipment_id character varying(50) COLLATE pg_catalog."default",
    is_vat_required boolean,
    note text COLLATE pg_catalog."default",
    order_status character varying(255) COLLATE pg_catalog."default",
    shipment_status_txt character varying(255) COLLATE pg_catalog."default",
    shipping_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    shipping_carrier character varying(50) COLLATE pg_catalog."default",
    shipping_city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    shipping_city_code character varying(20) COLLATE pg_catalog."default",
    shipping_district character varying(100) COLLATE pg_catalog."default" NOT NULL,
    shipping_district_code character varying(20) COLLATE pg_catalog."default",
    shipping_fee numeric(15, 2),
    shipping_status character varying(50) COLLATE pg_catalog."default",
    shipping_ward character varying(100) COLLATE pg_catalog."default" NOT NULL,
    shipping_ward_code character varying(20) COLLATE pg_catalog."default",
    tax_code character varying(50) COLLATE pg_catalog."default",
    total_amount numeric(15, 2) NOT NULL,
    tracking_number character varying(50) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    user_id integer,
    voucher_id integer,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT ukgt3o4a5bqj59e9y6wakgk926t UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.password_reset_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    attempts integer NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone NOT NULL,
    used boolean NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT password_reset_codes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount numeric(15, 2) NOT NULL,
    created_at timestamp(6) without time zone,
    method character varying(255) COLLATE pg_catalog."default" NOT NULL,
    provider_response text COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    transaction_code character varying(100) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    order_id integer NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_attribute_values
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    attribute_id integer NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT product_attribute_values_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_serials
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    inventory_note_id integer,
    order_id integer,
    product_variant_id integer NOT NULL,
    serial_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    CONSTRAINT product_serials_pkey PRIMARY KEY (id),
    CONSTRAINT uk4lldmknreiu8b3c58kieu7vha UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS public.product_variant_images
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    image_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_thumbnail boolean,
    sort_order integer,
    variant_id integer NOT NULL,
    CONSTRAINT product_variant_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_variants
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    is_default boolean NOT NULL,
    is_serial_required boolean NOT NULL,
    option1_value character varying(50) COLLATE pg_catalog."default",
    option2_value character varying(50) COLLATE pg_catalog."default",
    option3_value character varying(50) COLLATE pg_catalog."default",
    original_price numeric(15, 2),
    price numeric(15, 2) NOT NULL,
    sku character varying(100) COLLATE pg_catalog."default" NOT NULL,
    stock_quantity integer NOT NULL,
    weight numeric(10, 2),
    product_id integer NOT NULL,
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT ukq935p2d1pbjm39n0063ghnfgn UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    option1_name character varying(50) COLLATE pg_catalog."default",
    option2_name character varying(50) COLLATE pg_catalog."default",
    option3_name character varying(50) COLLATE pg_catalog."default",
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    thumbnail character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    warranty_period character varying(100) COLLATE pg_catalog."default",
    brand_id integer NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT ukostq1ec3toafnjok09y9l7dox UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment text COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    image character varying(1000) COLLATE pg_catalog."default",
    is_verified_purchase boolean NOT NULL,
    rating integer NOT NULL,
    product_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    avatar character varying(500) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    date_of_birth date,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(10) COLLATE pg_catalog."default",
    last_login timestamp(6) without time zone,
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    provider character varying(20) COLLATE pg_catalog."default",
    provider_id character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vouchers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    discount_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(15, 2) NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    max_discount_value numeric(15, 2),
    min_order_value numeric(15, 2),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    usage_limit integer,
    used_count integer,
    CONSTRAINT vouchers_pkey PRIMARY KEY (id),
    CONSTRAINT uk30ftp2biebbvpik8e49wlmady UNIQUE (code)
);

-- ==========================================
-- 2. THIẾT LẬP KHÓA NGOẠI (FOREIGN KEYS)
-- ==========================================

ALTER TABLE IF EXISTS public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT fkn1s4l7h0vm4o259wpu7ft0y2y FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id)
    REFERENCES public.carts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.chat_messages_ai
    ADD CONSTRAINT fk1942i18wj2y60s009hb5o6dd4 FOREIGN KEY (session_id)
    REFERENCES public.chat_session_ai (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.flash_sales
    ADD CONSTRAINT fke8d8imn1usru8ab78wi8pyal8 FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.inventory_note_details
    ADD CONSTRAINT fkjygd4wm6hp2q6e8579sqb5m1 FOREIGN KEY (inventory_note_id)
    REFERENCES public.inventory_notes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fkltmtlue0wixrg1cf0xo7x0l4d FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fkdimvsocblb17f45ikjr6xn1wj FOREIGN KEY (voucher_id)
    REFERENCES public.vouchers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.password_reset_codes
    ADD CONSTRAINT fkke97isexxbl8lf7yibo6q02ir FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.product_attribute_values
    ADD CONSTRAINT fk9cv255c78bptiixa9axev9act FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.product_attribute_values
    ADD CONSTRAINT fkdhipfhjpy3gq5wlo3vc2h8uf FOREIGN KEY (attribute_id)
    REFERENCES public.attributes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.product_variant_images
    ADD CONSTRAINT fk9jwla8t7mpnllbt5gp0le008i FOREIGN KEY (variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT fkosqitn4s405cynmhb87lkvuau FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fka3a4mpsfdf4d2y6r8ra3sc8mv FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkpl51cejpw4gy5swfar8br9ngi FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMIT;


-----------------------------------------------------------------------
-- ======================================================================
-- PHẦN 1: DỮ LIỆU DANH MỤC CƠ BẢN (Rất nhẹ, chạy trong 1 nốt nhạc)
-- ======================================================================
BEGIN;

INSERT INTO public.roles (name, description) VALUES 
    ('ROLE_CUSTOMER', 'Khách hàng thông thường'),
    ('ROLE_ADMIN', 'Quản trị viên hệ thống'),
    ('ROLE_MANAGER', 'Quản lý cửa hàng')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.categories (name, slug, description, status, created_at)
SELECT 'Danh mục ' || i, 'danh-muc-' || i, 'Mô tả cho danh mục ' || i, 'ACTIVE', NOW() - (random() * interval '365 days')
FROM generate_series(1, 20) AS i ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.brands (name, slug, description, logo_url, status, created_at)
SELECT 'Thương hiệu ' || i, 'thuong-hieu-' || i, 'Mô tả cho thương hiệu ' || i, 'https://example.com/logo-' || i || '.png', 'ACTIVE', NOW() - (random() * interval '365 days')
FROM generate_series(1, 30) AS i ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.attributes (name, code, filter_group, status) VALUES
('Màu sắc', 'color', 'COLOR', 'ACTIVE'), ('Kích thước', 'size', 'SIZE', 'ACTIVE'), ('Chất liệu', 'material', 'MATERIAL', 'ACTIVE');

COMMIT;


-- ======================================================================
-- PHẦN 2: USERS (1 TRIỆU DÒNG) & QUYỀN
-- Ghi chú: Chốt 1 triệu user để test mượt mà và không tốn quá nhiều ổ cứng
-- ======================================================================
BEGIN;

INSERT INTO public.users (username, email, password, gender, phone, status, created_at, updated_at)
SELECT 
    'customer_' || seq, 
    'customer_' || seq || '_' || substr(md5(random()::text), 1, 5) || '@gmail.com', 
    md5(random()::text), 
    CASE WHEN random() > 0.5 THEN 'MALE' ELSE 'FEMALE' END, 
    '09' || lpad((random() * 100000000)::int::text, 8, '0'), 
    CASE WHEN random() > 0.05 THEN 'ACTIVE' ELSE 'INACTIVE' END, 
    NOW() - (random() * interval '5 years'), 
    NOW()
FROM generate_series(1, 1000000) AS seq; -- Đã sửa thành 1 triệu

INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, (SELECT id FROM public.roles WHERE name = 'ROLE_CUSTOMER')
FROM public.users u WHERE u.username LIKE 'customer_%';

COMMIT;


-- ======================================================================
-- PHẦN 3: SẢN PHẨM, BIẾN THỂ & VOUCHER
-- ======================================================================
BEGIN;

INSERT INTO public.products (name, slug, description, status, brand_id, category_id, created_at, updated_at)
SELECT 'Sản phẩm cao cấp ' || i, 'san-pham-cao-cap-' || i, 'Mô tả chi tiết cho sản phẩm ' || i, 'ACTIVE',
    floor(random() * 30 + 1)::int, floor(random() * 20 + 1)::int, NOW() - (random() * interval '2 years'), NOW()
FROM generate_series(1, 10000) AS i;

INSERT INTO public.product_variants (sku, price, stock_quantity, is_default, is_serial_required, product_id, created_at)
SELECT 'SKU-' || i || '-' || floor(random() * 9999), floor(random() * 5000000 + 100000), floor(random() * 1000), 
    CASE WHEN i % 3 = 0 THEN true ELSE false END, false, floor(random() * 10000 + 1)::int, NOW()
FROM generate_series(1, 30000) AS i;

INSERT INTO public.vouchers (code, name, discount_type, discount_value, start_date, end_date, created_at)
SELECT 'VOUCHER' || i, 'Giảm giá ' || i || ' %', 'PERCENT', floor(random() * 50 + 5), NOW() - interval '10 days', NOW() + interval '30 days', NOW()
FROM generate_series(1, 50) AS i;

COMMIT;


-- ======================================================================
-- PHẦN 4: GIAO DỊCH (ORDERS, ADDRESSES, REVIEWS)
-- Đã đồng bộ random trỏ về giới hạn 1,000,000 users thay vì 5,000,000
-- ======================================================================
BEGIN;

-- 50k địa chỉ
INSERT INTO public.addresses (full_name, phone, address_detail, city, district, ward, user_id, is_default)
SELECT 'Người nhận ' || i, '09' || lpad((random() * 100000000)::int::text, 8, '0'), 'Số ' || floor(random() * 999 + 1) || ' Đường số ' || floor(random() * 20 + 1),
    'Hồ Chí Minh', 'Quận 1', 'Phường Bến Nghé',
    floor(random() * 1000000 + 1)::int, -- ĐỒNG BỘ: max 1 triệu user
    true
FROM generate_series(1, 50000) AS i;

-- 100k đơn hàng
INSERT INTO public.orders (code, customer_name, customer_phone, shipping_address, shipping_city, shipping_district, shipping_ward, total_amount, final_amount, user_id, voucher_id, created_at)
SELECT 'ORD-' || i || '-' || floor(random() * 9999), 'Khách mua hàng ' || i, '09' || lpad((random() * 100000000)::int::text, 8, '0'), 'Địa chỉ giao hàng ' || i,
    'Hà Nội', 'Cầu Giấy', 'Dịch Vọng', floor(random() * 10000000 + 200000), floor(random() * 9000000 + 200000), 
    floor(random() * 1000000 + 1)::int, -- ĐỒNG BỘ: max 1 triệu user
    CASE WHEN random() > 0.8 THEN floor(random() * 50 + 1)::int ELSE NULL END, NOW() - (random() * interval '1 year')
FROM generate_series(1, 100000) AS i;

-- 50k lượt đánh giá
INSERT INTO public.reviews (user_id, product_id, rating, comment, is_verified_purchase, created_at)
SELECT 
    floor(random() * 1000000 + 1)::int, -- ĐỒNG BỘ: max 1 triệu user
    floor(random() * 10000 + 1)::int, floor(random() * 5 + 1)::int, 'Sản phẩm rất tốt, đáng tiền mua. Giao hàng nhanh!', true, NOW() - (random() * interval '6 months')
FROM generate_series(1, 50000) AS i;

COMMIT;


-- ======================================================================
-- PHẦN 5: CHI TIẾT GIAO DỊCH (ORDER ITEMS & PAYMENTS)
-- ======================================================================
BEGIN;

INSERT INTO public.order_items (order_id, product_variant_id, product_name, quantity, price, total_price)
SELECT floor(random() * 100000 + 1)::int, floor(random() * 30000 + 1)::int, 'Sản phẩm trong đơn ' || i, floor(random() * 5 + 1), 500000, 500000 * floor(random() * 5 + 1)
FROM generate_series(1, 250000) AS i;

INSERT INTO public.payments (order_id, method, amount, status, created_at)
SELECT id, CASE WHEN random() > 0.5 THEN 'COD' ELSE 'VNPAY' END, final_amount, CASE WHEN random() > 0.1 THEN 'SUCCESS' ELSE 'PENDING' END, created_at
FROM public.orders;

COMMIT;




-- ======================================================================
-- PHẦN 6: LUỒNG NHẬP KHO (INVENTORY NOTES & HISTORY)
-- Bao gồm: Phiếu nhập kho, Chi tiết phiếu nhập, Lịch sử biến động kho
-- ======================================================================
BEGIN;

-- 1. TẠO 5,000 PHIẾU NHẬP KHO (INVENTORY_NOTES)
-- Giả lập các lần nhập hàng từ nhà cung cấp
INSERT INTO public.inventory_notes (code, type, reason, status, supplier_name, total_amount, user_id, created_at)
SELECT 
    'PNK-' || i || '-' || floor(random() * 9999), -- Mã phiếu nhập (VD: PNK-1-4521)
    'INWARD',                                     -- INWARD: Nhập kho, OUTWARD: Xuất kho
    'Nhập hàng định kỳ tháng',
    'COMPLETED',                                  -- Trạng thái hoàn tất
    'Nhà cung cấp ' || floor(random() * 50 + 1),  -- Random 50 nhà cung cấp
    floor(random() * 50000000 + 5000000),         -- Tổng tiền nhập (5tr - 55tr)
    floor(random() * 1000000 + 1)::int,           -- ĐỒNG BỘ: User tạo phiếu (trong 1 triệu user)
    NOW() - (random() * interval '1 year')        -- Ngày tạo ngẫu nhiên trong 1 năm qua
FROM generate_series(1, 5000) AS i;

-- 2. TẠO 15,000 CHI TIẾT PHIẾU NHẬP (INVENTORY_NOTE_DETAILS)
-- Mỗi phiếu nhập ở trên sẽ có trung bình 3 mã sản phẩm (biến thể)
INSERT INTO public.inventory_note_details (inventory_note_id, product_variant_id, quantity, price)
SELECT 
    floor(random() * 5000 + 1)::int,  -- Trỏ ngẫu nhiên về 5,000 phiếu nhập vừa tạo
    floor(random() * 30000 + 1)::int, -- ĐỒNG BỘ: Trỏ về 30,000 product_variants
    floor(random() * 100 + 10)::int,  -- Nhập số lượng từ 10 đến 110 sản phẩm
    floor(random() * 2000000 + 50000) -- Giá nhập ngẫu nhiên (50k - 2tr)
FROM generate_series(1, 15000) AS i;

-- 3. TẠO LỊCH SỬ BIẾN ĐỘNG KHO (INVENTORY_HISTORY)
-- Sinh tự động dựa trên bảng Chi tiết phiếu nhập vừa tạo để đảm bảo logic 100%
INSERT INTO public.inventory_history (product_variant_id, reference_type, reference_id, change_amount, previous_quantity, new_quantity, note, created_at)
SELECT 
    product_variant_id,
    'INVENTORY_NOTE',      -- Loại thao tác: Qua phiếu kiểm/nhập kho
    inventory_note_id,     -- ID của phiếu nhập
    quantity,              -- Số lượng thay đổi (dấu dương vì là nhập kho)
    0,                     -- (Giả lập) Tồn kho trước đó là 0
    quantity,              -- Tồn kho mới bằng chính số lượng nhập
    'Hệ thống tự động ghi nhận nhập kho từ phiếu ID: ' || inventory_note_id,
    NOW() - (random() * interval '1 year')
FROM public.inventory_note_details;

COMMIT;



SELECT * FROM pg_stat_activity WHERE query LIKE '%autovacuum%';

SELECT pid, state, backend_type, query
FROM pg_stat_activity
WHERE state != 'idle';

SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE query LIKE '%FROM products p%'
AND pid <> pg_backend_pid();

EXPLAIN ANALYZE SELECT 
    p.id,
    p.name,
    p.slug,
    p.thumbnail,
    pv.price,
    pv.original_price AS "originalPrice",

    -- rating
    (
        SELECT COALESCE(AVG(r.rating), 0.0)
        FROM reviews r
        WHERE r.product_id = p.id
          AND r.deleted_at IS NULL
    ) AS rating,

    -- review count
    (
        SELECT COUNT(r.id)
        FROM reviews r
        WHERE r.product_id = p.id
          AND r.deleted_at IS NULL
    ) AS "reviewCount",

    -- stock
    (
        SELECT COALESCE(SUM(pv_all.stock_quantity), 0)
        FROM product_variants pv_all
        WHERE pv_all.product_id = p.id
          AND pv_all.deleted_at IS NULL
    ) AS "stockQuantity",

    -- is new
    CASE 
        WHEN p.created_at >= NOW() - INTERVAL '30 days' THEN 1 
        ELSE 0 
    END AS "isNew",

    -- specs
    CONCAT_WS(', ', pv.option1_value, pv.option2_value, pv.option3_value) AS "specsStr"

FROM products p

LEFT JOIN product_variants pv ON pv.id = (
    SELECT v.id
    FROM product_variants v
    WHERE v.product_id = p.id
      AND v.deleted_at IS NULL
    ORDER BY v.is_default DESC, v.price ASC
    LIMIT 1
)

WHERE p.status = 'ACTIVE'
  AND p.deleted_at IS NULL

ORDER BY (
    SELECT COALESCE(SUM(oi.quantity), 0)
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.id
    WHERE oi.product_variant_id = pv.id
      AND o.order_status = 'COMPLETED'
) DESC

LIMIT 10;

EXPLAIN ANALYZE SELECT *
FROM product_card_view pc
ORDER BY (
    SELECT COALESCE(SUM(oi.quantity), 0)
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.id
    WHERE oi.product_variant_id = pc.variant_id
      AND o.order_status = 'COMPLETED'
) DESC
LIMIT 20;

CREATE INDEX idx_order_items_variant_id ON order_items(product_variant_id);
CREATE INDEX idx_orders_status ON orders(order_status);
CREATE INDEX idx_order_items_variant_order ON order_items(product_variant_id, order_id);
CREATE INDEX idx_reviews_product_id ON reviews(product_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_variants_product_default_price ON product_variants(product_id, is_default DESC, price ASC) WHERE deleted_at IS NULL;
CREATE INDEX idx_products_active ON products(status)WHERE deleted_at IS NULL;

CREATE INDEX idx_orders_status_id ON orders(order_status, id);
CREATE INDEX idx_order_items_covering ON order_items(product_variant_id, order_id, quantity);

